enum Operacoes {
  ADMINISTRATIVA,
  CANCELAMENTO,
  CANCELAMENTO_PAGAMENTOCONTA,
  CANCELAMENTO_PREAUTORIZACAO,
  CONFIGURACAO,
  CONSULTA_CHEQUE,
  CONSULTA_SALDO,
  DOACAO,
  EXIBE_PDC,
  FECHAMENTO,
  GARANTIA_CHEQUE,
  INSTALACAO,
  MANUTENCAO,
  OPERACAO_DESCONHECIDA,
  PAGAMENTO_CONTA,
  PREAUTORIZACAO,
  RECARGA_CELULAR,
  REIMPRESSAO,
  RELATORIO_DETALHADO,
  RELATORIO_RESUMIDO,
  RELATORIO_SINTETICO,
  SAQUE,
  TESTE_COMUNICACAO,
  VENDA,
  VERSAO,
}

enum Cartoes {
  CARTAO_CREDITO,
  CARTAO_DEBITO,
  CARTAO_DESCONHECIDO,
  CARTAO_FROTA,
  CARTAO_PRIVATELABEL,
  CARTAO_VOUCHER,
}

enum Financiamentos {
  A_VISTA,
  CREDITO_EMISSOR,
  FINANCIAMENTO_NAO_DEFINIDO,
  PARCELADO_EMISSOR,
  PARCELADO_ESTABELECIMENTO,
  PRE_DATADO,
}

enum ModalidadesPagamento {
  CARTEIRA_VIRTUAL,
  PAGAMENTO_CARTAO,
  PAGAMENTO_CHEQUE,
  PAGAMENTO_DINHEIRO,
}

enum DialogText {
  ERRO_IMPRESSAO,
  ERRO_OPERACAO,
  RETORNO,
  IMPRESSAO_CLIENTE,
}

enum ModalidadesTransacao {
  ON,
  OFF,
}

enum ViasImpressao {
  VIA_CLIENTE,
  VIA_CLIENTE_E_ESTABELECIMENTO,
  VIA_ESTABELECIMENTO,
  VIA_NENHUMA,
}

enum StatusTransacao {
  CONFIRMADO_AUTOMATICO,
  CONFIRMADO_MANUAL,
  DESFEITO_ERRO_IMPRESSAO_AUTOMATICO,
  DESFEITO_LIBERACAO_MERCADORIA,
  DESFEITO_MANUAL,
  STATUS_TRANSACAO_NAO_DEFINIDO,
}
